### ISSUE TITLE
Add Commit Stats

### ISSUE THREAD

**Issue by mustafaozhan** [ashkulz/committers.top#11]
Hello 👋 

After our discussion here: https://github.com/lauripiispanen/most-active-github-users-counter/issues/148#issuecomment-1346369642

I wanted to ask if it is possible to add the Commit Badges also in this repository, I think it is really cool feature.

There is already 1 repo for that, but It stops working for me even though I am a listed user in Germany in committers.top.

Here is the repo: https://github.com/fbiego/commits-top-badge.

The author seems not caring the repo anymore, since my last created issue didn't get any feedback.

**Comment by ashkulz** [comment]
@mustafaozhan see [my previous comment](https://github.com/ashkulz/committers.top/issues/3#issuecomment-1028514989) -- I'm not generating the badge myself, instead using `shields.io` for the badges. If you can generate the SVG yourself dynamically, please add the code to the [CF Worker](https://github.com/ashkulz/committers.top/blob/master/badges/cloudflare_worker.js). Alternatively, I'll need some to have some site which has _some_ uptime guarantees to source the badge from.

**Comment by mustafaozhan** [comment]
Hey hello @ashkulz thank you for your response, I understand, I created a feature request to here: https://github.com/anuraghazra/github-readme-stats/issues/2356

Let's hope maybe they can do it.

**Comment by ashkulz** [comment]
Cool, so I guess nothing to be here then?

**Comment by mustafaozhan** [comment]
Nope, thank you 🙂
