### ISSUE TITLE
Remove peple that uses bots.  

### ISSUE THREAD

**Issue by garronej** [ashkulz/committers.top#24]
Hello, thanks a lot for this project. It can be used as a negotiation tools!  

I noticed however that the first places are ofter trusted by pepole obviously using bots like: 
https://github.com/philou  or https://github.com/pocky  

Not to dunk on them on any way, I'm sure it wasn't their intent to highjack the system but automatic commit shouldn't count.  

To easily mitigate this there could be a threshold, pepole that have an average commit per day over 30 could resonably be filtered out.

**Comment by garronej** [comment]
Or we could filter out pepole that obviously uses bot. I can submit a PR if you're open to the idea

**Comment by ashkulz** [comment]
@garronej please see the discussion in #22 -- I'm not sure that's really possible without changes in the GitHub API. That said, if you do find a way to improve the status quo by any means, I would be **very** happy to merge any PRs!

I think this is something that's worth adding to the FAQ in the readme, would appreciate contributions 😄. That said, I'm closing this for now.

**Comment by garronej** [comment]
@ashkulz understood, thanks!
