### ISSUE TITLE
Refresh Cycle

### ISSUE THREAD

**Issue by DevAdriam** [ashkulz/committers.top#26]
Even i reached 1k contributions it still didn't change from 100 contributions in list!

**Comment by ashkulz** [comment]
@DevAdriam, did you see this [entry in the FAQ](https://github.com/ashkulz/committers.top?tab=readme-ov-file#why-am-i-not-on-this-list)?

**Comment by DevAdriam** [comment]
> @DevAdriam, did you see this [entry in the FAQ](https://github.com/ashkulz/committers.top?tab=readme-ov-file#why-am-i-not-on-this-list)?

I already read this , and test it's graphql api my contribution is over 1k
