### ISSUE TITLE
Verbose mode

### ISSUE THREAD

**Issue by Sigmanificient** [ashkulz/committers.top#27]
Hi, I have played around with your tool, and it seems to take a really long time despite my good connection.
I suspect that it does a lot of queries behind the scene, and maybe it gets rate-limited? 

I used the command from the README, and increased slightly the amount, in hope to see my profile appear on the list:

```bash
go run *.go          \
    --token [TOKEN]  \
    --preset france  \
    --amount 5000    \
    --consider 10000 \
    --output csv     \
    --file ./output.csv
```

Could you add something like a verbose mode to see what is happening, and possibly track progression?
It would be really nice! Thanks

**Comment by ashkulz** [comment]
@Sigmanificient did you try [this GraphQL query](https://github.com/ashkulz/committers.top?tab=readme-ov-file#why-is-my-contribution-count-not-the-same-as-on-my-github-profile)? Also, if you read the [page for France](https://committers.top/france) it clearly states you need to be having 164 followers to be on the list, which doesn't seem to be the case for you. See [this FAQ entry](https://github.com/ashkulz/committers.top?tab=readme-ov-file#why-am-i-not-on-this-list) on why this is done.

**Comment by Sigmanificient** [comment]
Hi, I don't understand your reply, as it seems to be unrelated with the issue I opened and feature request I proposed?
