### ISSUE TITLE
I am on the list, but badge shows "unranked"

### ISSUE THREAD

**Issue by Joknaa** [ashkulz/committers.top#29]
Hi, 

I am currently rank 219 in this list: https://committers.top/morocco_private

But the badge shows unranked for some reason: https://user-badge.committers.top/morocco_private/joknaa.svg

**Comment by ashkulz** [comment]
Hmm, you're right. Let me take a look.

**Comment by ashkulz** [comment]
Whoops, you need to use the right case:

<img src="https://user-badge.committers.top/morocco_private/Joknaa.svg">

**Comment by Joknaa** [comment]
Is there any way to customise the style ?  "style=for-the-badge"

<img align="center" src="https://komarev.com/ghpvc/?username=joknaa&label=Profile%20views&color=0e75b6&style=for-the-badge"/>

**Comment by ashkulz** [comment]
I'm not averse to accepting a PR, see [this previous comment](https://github.com/ashkulz/committers.top/issues/3#issuecomment-1028514989).
