### ISSUE TITLE
New Badge

### ISSUE THREAD

**Issue by fbiego** [ashkulz/committers.top#3]
Is it possible to integrate this badge from [`commits-top-badge`](https://github.com/fbiego/commits-top-badge) to this project?

```
![commits.top ranking](http://biego.tech/commits?user=fbiego&country=kenya&bg_color=333333&text_color=77fe89&border_color=89452e)
```
![committers.top ranking](http://biego.tech/commits?user=fbiego&country=kenya&bg_color=333333&text_color=77fe89&border_color=89452e)

**Comment by ashkulz** [comment]
@fbiego I'm not sure which of the options below you meant:
1. mention the above markdown as an alternative in the generated site
2. actually generate the badge itself [via the CF Worker](https://github.com/ashkulz/committers.top/blob/master/badges/cloudflare_worker.js)

If it's option 1, I'm not averse to linking to a landing page on your site which allows a user to build the badge.

If it's option 2, I think I like the current badge a bit more, yours feels too big. I'm not averse to loading it if given a `variant=XXX` query string and from the above URL, but I'm not sure about the uptime of your site (btw, why isn't the URL HTTPS?) as compared to `shields.io`. I'd have preferred to generate the SVG directly from the worker, but I wasn't sure about the widths etc and just pushed the problem elsewhere :slightly_smiling_face:

**Comment by ashkulz** [comment]
Please re-open if you can respond to the above comment, as I'm not sure what needs to happen here
