### ISSUE TITLE
#CronJob - Daily Updates On the yml file

### ISSUE THREAD

**Issue by Katumbela** [ashkulz/committers.top#36]
Looks like the update is made randomly , or even 4 - 4 days 
was not suposed to be updated daily ?

**Comment by ashkulz** [comment]
See [this comment](https://github.com/ashkulz/committers.top/issues/4#issuecomment-1107347500) -- the job runs every hour but only [refreshes after 5 days](https://github.com/ashkulz/committers.top/blob/94891736d00051cd16fcc7d159fb3e211019661d/.github/workflows/daily_update.yml#L33).

**Comment by Katumbela** [comment]
got it, cool
