### ISSUE TITLE
Reduce the minimum requirement for followers

### ISSUE THREAD

**Issue by DefinetlyNotAI** [ashkulz/committers.top#39]
Can you reduce the minimum to 20 followers?

Its just hard to get followers and I think 20 is fine,

**Comment by ashkulz** [comment]
@DefinetlyNotAI I'm not sure which country you're talking about, but please [see the FAQ](https://github.com/ashkulz/committers.top?tab=readme-ov-file#why-am-i-not-on-this-list) -- it all depends on the API.

**Comment by DefinetlyNotAI** [comment]
Ahh, my bad - I thought you guys introduced the follower limit, misread the FAQ, thanks
