### ISSUE TITLE
Ability to report *cheaters*

### ISSUE THREAD

**Issue by abdulrahman1s** [ashkulz/committers.top#7]
We need a way to exclude/report cheaters :(

### I've found
- [MrAhmedSayedAli](https://github.com/MrAhmedSayedAli)
  - [cpp-test](https://github.com/MrAhmedSayedAli/cpp-test)
  - [CPP-TEST-TOW](https://github.com/MrAhmedSayedAli/CPP-TEST-TOW)
- [fadyehabamer](https://github.com/fadyehabamer)
  - [GithubCommits](https://github.com/fadyehabamer/GithubCommits)
- [BitTheByte](https://github.com/BitTheByte)
  - [LetsFoolBots](https://github.com/BitTheByte/LetsFoolBots)
- [Salah856](https://github.com/Salah856)
  - [Salah856](https://github.com/Salah856/Salah856)
  
By excluding those people and those who are like them, we'll achieve the real goal of this project.
\* We may contact them before taking any action.

**Comment by ashkulz** [comment]
This is related to lauripiispanen/most-active-github-users-counter#153 -- how would the tool know that the commits are fake? Maintaining a list is going to be complicated and require people to review it manually, which I don't think will scale.

**Comment by abdulrahman1s** [comment]
I understand your point. maybe in the future someone will make a fake commits detector, who knows.
and thanks for your hard work on this project <3
