### ISSUE TITLE
[Feature] Add country to badge

### ISSUE THREAD

**Issue by RaheemAmer** [ashkulz/committers.top#8]
## Badge
- The badge currently looks like this, is there a way to add the country next to it?
![image](https://user-images.githubusercontent.com/18606136/192936784-0e51159f-e9b9-4bf7-87be-47397f19762d.png)

## For Example 
-  commiters.top rank Egypt

**Comment by ashkulz** [comment]
Do you mean something like `committers.top rank|egypt #9`? I'd welcome a PR which does that, you just need to modify [this line](https://github.com/ashkulz/committers.top/blob/ff9cd2dd174b8781b0f235aff375ba8d2bafa890/badges/cloudflare_worker.js#L22).

**Comment by RaheemAmer** [comment]
@ashkulz Exactly yes, I'll give it a go and try my best with it.
Thank you ❤️
